baseurl = "https://paolomainardi.com"
title = "Paolo Mainardi"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

enableRobotsTXT = true
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = ""
enableEmoji = true

[pagination]
pagerSize = 20

[module]
[[module.imports]]
path = "cj.rs/gohugo-asciinema"

[params]
author = "Paolo Mainardi"
info = "Founder and CTO of [@Sparkfabrik](https://www.sparkfabrik.com)"
description = "Welcome to my personal blog. I'm Paolo Mainardi, Founder and CTO of Sparkfabrik. I write about Containers, Kubernetes, Linux and cloud-native stuff."
keywords = "blog,developer,personal"
avatarurl = "images/me.jpg"
headTitle = "Paolo Mainardi | Founder and CTO of Sparkfabrik"

colorScheme = "auto"

customCSS = ["css/custom.css"]
customRemoteJS = ["https://unpkg.com/hugo-lyra@0.4.2/dist/browser/hugo-lyra.js"]

favicon_32 = "/images/favicon-32x32.png"
favicon_16 = "/images/favicon-16x16.png"
touchicon = "/images/apple-touch-icon.png"
manifest = "/site.webmanifest"

footercontent = "Writing about Containers, Kubernetes, Linux and cloud-native stuff"

hidecredits = false
hidecopyright = false
since = 2020

rtl = false
math = true

# Custom CSS
custom_css = []

# Custom JS
custom_js = []


# Social links
[[params.social]]
name = "RSS Feed"
icon = "fa fa-rss fa-2x"
weight = 1
url = "https://www.paolomainardi.com/posts/index.xml"
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 2
url = "https://github.com/paolomainardi"
[[params.social]]
name = "Gitlab"
icon = "fa fa-gitlab fa-2x"
weight = 3
url = "https://gitlab.com/paolomainardi"
[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 4
url = "https://twitter.com/paolomainardi"


# Menu links
[[menu.main]]
name = "Posts"
weight = 1
url = "posts/"
[[menu.main]]
name = "Talks"
weight = 2
url = "/talks"
[[menu.main]]
name = "About"
weight = 3
url = "/about"

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = true
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'dracula'
tabWidth = 4

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
disable = true
